# Generated by Django 4.0.5 on 2022-06-21 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='exposure_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='노출 종료 일자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='exposure_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='노출 시작 일자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='blog.category', verbose_name='category'),
        ),
    ]
